language: objective-c
cache:
  directories:
    - Example/vendor/bundle
install:
  - (cd Example && bundle install --path=vendor/bundle --binstubs=vendor/bin)
script:
  - (cd Example && pod install && bundle exec rake build test)
env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
